language: python
python:
 - "3.6"
install:
 - pip install -r requirements.txt 
 - pip install pytest
 - pip install coveralls
script:
 - pytest
 - nosetests -v --with-coverage --cover-package=api
after_success: 
 - coveralls
