language:
python:
  - "3.6"
cache: pip
# command to install dependencies

before_script:
  - psql -c 'create database mydiary;' -U postgres
install:
  - pip install --upgrade
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage
  - pip install nose

services:
  - postgresql

script:
  - pytest 
  - nosetests --with-coverage

after_success:
  - coveralls
