language:
python:
  - "3.6"
cache: pip
# command to install dependencies

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - psql -c 'create database mydiary;' -U postgres
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage
  - pip install nose

services:
  - postgresql

script:
  - pytest 
  - nosetests --with-coverage

after_success:
  - coveralls
