FORMAT: 1A
HOST: https://www.theskaterdev.com

#The Diario Entry Blog Posts
This is the Blog posts API for retrieving  blog posts

#Group Posts

#Group Users

## Posts Collection [/posts]

### Get All posts [GET/Posts]
+ Response 200 (application/json)
    + Attributes
        - id: '1' (number) - The ID of the post
        - title: 'My awesome blog post' (string) - The title of the post